content = []
content.append('from utils.ollama_client import chat, extract_json, extract_confidence')
content.append('from config import MODEL_HEAVY')
content.append('')
content.append('BULL_SYSTEM = (')
content.append('    ' + chr(39) + 'You are a veteran gold BULL trader. XAU/USD specialist. ' + chr(39))
content.append('    ' + chr(39) + 'Build the STRONGEST case for gold RISING in 24-48h. ' + chr(39))
content.append('    ' + chr(39) + 'Use ALL provided data: price, RSI, news headlines. Be specific. ' + chr(39))
content.append('    ' + chr(39) + 'You MUST respond in this exact JSON format and nothing else: ' + chr(39))
content.append('    ' + chr(39) + '{' + chr(34) + 'argument' + chr(34) + ': ' + chr(34) + 'your full bull argument here' + chr(34) + ', ' + chr(34) + 'confidence' + chr(34) + ': 72, ' + chr(34) + 'price_target' + chr(34) + ': 4900}' + chr(39))
content.append(')')
content.append('')
content.append('BEAR_SYSTEM = (')
content.append('    ' + chr(39) + 'You are a veteran gold BEAR trader. XAU/USD specialist. ' + chr(39))
content.append('    ' + chr(39) + 'Build the STRONGEST case for gold FALLING in 24-48h. ' + chr(39))
content.append('    ' + chr(39) + 'Use ALL provided data: price, RSI, news headlines. Be specific. ' + chr(39))
content.append('    ' + chr(39) + 'You MUST respond in this exact JSON format and nothing else: ' + chr(39))
content.append('    ' + chr(39) + '{' + chr(34) + 'argument' + chr(34) + ': ' + chr(34) + 'your full bear argument here' + chr(34) + ', ' + chr(34) + 'confidence' + chr(34) + ': 68, ' + chr(34) + 'price_target' + chr(34) + ': 4600}' + chr(39))
content.append(')')
content.append('')
content.append('def _ctx(macro, tech, price, news):')
content.append('    p = price.get(' + chr(39) + 'price' + chr(39) + ', 0)')
content.append('    ni = news.get(' + chr(39) + 'news_items' + chr(39) + ', []) if news else []')
content.append('    headlines = chr(10).join([' + chr(39) + '- ' + chr(39) + ' + x[' + chr(39) + 'title' + chr(39) + '] for x in ni[:8]]) if ni else ' + chr(39) + 'No headlines' + chr(39))
content.append('    return chr(10).join([')
content.append('        ' + chr(39) + '=== MARKET DATA ===' + chr(39) + ',')
content.append('        ' + chr(39) + 'XAU/USD: $' + chr(39) + ' + str(p) + ' + chr(39) + ' | Change: ' + chr(39) + ' + str(price.get(' + chr(39) + 'change_pct' + chr(39) + ',0)) + ' + chr(39) + '% | H:' + chr(39) + ' + str(price.get(' + chr(39) + 'high' + chr(39) + ',p)) + ' + chr(39) + ' L:' + chr(39) + ' + str(price.get(' + chr(39) + 'low' + chr(39) + ',p)),')
content.append('        ' + chr(39) + 'RSI(14): ' + chr(39) + ' + str(tech.get(' + chr(39) + 'rsi_value' + chr(39) + ')) + ' + chr(39) + ' | Trend: ' + chr(39) + ' + str(tech.get(' + chr(39) + 'trend' + chr(39) + ')) + ' + chr(39) + ' | SMA20: ' + chr(39) + ' + str(tech.get(' + chr(39) + 'sma20' + chr(39) + ')),')
content.append('        ' + chr(39) + 'Support: $' + chr(39) + ' + str(tech.get(' + chr(39) + 'support' + chr(39) + ')) + ' + chr(39) + ' | Resistance: $' + chr(39) + ' + str(tech.get(' + chr(39) + 'resistance' + chr(39) + ')),')
content.append('        ' + chr(39) + 'Macro: ' + chr(39) + ' + str(macro.get(' + chr(39) + 'macro_bias' + chr(39) + ')) + ' + chr(39) + ' (' + chr(39) + ' + str(macro.get(' + chr(39) + 'confidence' + chr(39) + ')) + ' + chr(39) + '%) | Drivers: ' + chr(39) + ' + str(macro.get(' + chr(39) + 'key_drivers' + chr(39) + ,[])[:3]),')
content.append('        ' + chr(39) + 'News sentiment: ' + chr(39) + ' + str(news.get(' + chr(39) + 'sentiment' + chr(39) + ', ' + chr(39) + 'NEUTRAL' + chr(39) + ') if news else ' + chr(39) + 'NEUTRAL' + chr(39) + '),')
content.append('        ' + chr(39) + '=== BREAKING HEADLINES ===' + chr(39) + ',')
content.append('        headlines,')
content.append('        ' + chr(39) + chr(39) + ',')
content.append('        ' + chr(39) + 'Respond ONLY in JSON. Your confidence must reflect the actual market conditions above.' + chr(39))
content.append('    ])')
content.append('')
content.append('def _parse_response(raw, fallback_conf):')
content.append('    result = extract_json(raw)')
content.append('    if result and ' + chr(39) + 'confidence' + chr(39) + ' in result:')
content.append('        conf = int(result[' + chr(39) + 'confidence' + chr(39) + '])')
content.append('        if 35 <= conf <= 95: return result[' + chr(39) + 'argument' + chr(39) + '], conf')
content.append('    conf = extract_confidence(raw)')
content.append('    return raw[:400], conf if conf != 57 else fallback_conf')
content.append('')
content.append('def run_debate(macro_data, tech_data, price_data, news_data=None):')
content.append('    if news_data is None: news_data = {}')
content.append('    ctx = _ctx(macro_data, tech_data, price_data, news_data)')
content.append('    history, bull_scores, bear_scores = [], [], []')
content.append('    sentiment = news_data.get(' + chr(39) + 'sentiment' + chr(39) + ', ' + chr(39) + 'NEUTRAL' + chr(39) + ')')
content.append('    macro_bias = macro_data.get(' + chr(39) + 'macro_bias' + chr(39) + ', ' + chr(39) + 'NEUTRAL' + chr(39) + ')')
content.append('    rsi = tech_data.get(' + chr(39) + 'rsi_value' + chr(39) + ', 50) or 50')
content.append('    bull_base = 65 if sentiment == ' + chr(39) + 'BULLISH_GOLD' + chr(39) + ' or macro_bias == ' + chr(39) + 'BULLISH' + chr(39) + ' else (52 if macro_bias == ' + chr(39) + 'NEUTRAL' + chr(39) + ' else 45)')
content.append('    bear_base = 65 if sentiment == ' + chr(39) + 'BEARISH_GOLD' + chr(39) + ' or rsi > 70 else (55 if rsi > 60 else 48)')
content.append('    r1_bull = chat(ctx + chr(10) + ' + chr(39) + 'Make your BULL case. JSON only.' + chr(39) + ', model=MODEL_HEAVY, system=BULL_SYSTEM, temperature=0.75)')
content.append('    r1_bear = chat(ctx + chr(10) + ' + chr(39) + 'Make your BEAR case. JSON only.' + chr(39) + ', model=MODEL_HEAVY, system=BEAR_SYSTEM, temperature=0.75)')
content.append('    a1b, bs1 = _parse_response(r1_bull, bull_base)')
content.append('    a1r, br1 = _parse_response(r1_bear, bear_base)')
content.append('    bull_scores.append(bs1); bear_scores.append(br1)')
content.append('    history.append({' + chr(39) + 'round' + chr(39) + ': 1, ' + chr(39) + 'bull' + chr(39) + ': a1b, ' + chr(39) + 'bear' + chr(39) + ': a1r})')
content.append('    print(' + chr(39) + '      Round 1 -- Bull: ' + chr(39) + ' + str(bs1) + ' + chr(39) + '% | Bear: ' + chr(39) + ' + str(br1) + ' + chr(39) + '%' + chr(39) + ')')
content.append('    r2_bull = chat(ctx + chr(10) + ' + chr(39) + 'Bear argued: ' + chr(39) + ' + a1r[:300] + chr(10) + ' + chr(39) + 'Refute and strengthen. JSON only.' + chr(39) + ', model=MODEL_HEAVY, system=BULL_SYSTEM, temperature=0.7)')
content.append('    r2_bear = chat(ctx + chr(10) + ' + chr(39) + 'Bull argued: ' + chr(39) + ' + a1b[:300] + chr(10) + ' + chr(39) + 'Refute and strengthen. JSON only.' + chr(39) + ', model=MODEL_HEAVY, system=BEAR_SYSTEM, temperature=0.7)')
content.append('    a2b, bs2 = _parse_response(r2_bull, bull_base)')
content.append('    a2r, br2 = _parse_response(r2_bear, bear_base)')
content.append('    bull_scores.append(bs2); bear_scores.append(br2)')
content.append('    history.append({' + chr(39) + 'round' + chr(39) + ': 2, ' + chr(39) + 'bull' + chr(39) + ': a2b, ' + chr(39) + 'bear' + chr(39) + ': a2r})')
content.append('    print(' + chr(39) + '      Round 2 -- Bull: ' + chr(39) + ' + str(bs2) + ' + chr(39) + '% | Bear: ' + chr(39) + ' + str(br2) + ' + chr(39) + '%' + chr(39) + ')')
content.append('    r3_bull = chat(ctx + chr(10) + ' + chr(39) + 'FINAL ROUND. Bear best: ' + chr(39) + ' + a2r[:200] + chr(10) + ' + chr(39) + 'Final verdict. JSON only.' + chr(39) + ', model=MODEL_HEAVY, system=BULL_SYSTEM, temperature=0.65)')
content.append('    r3_bear = chat(ctx + chr(10) + ' + chr(39) + 'FINAL ROUND. Bull best: ' + chr(39) + ' + a2b[:200] + chr(10) + ' + chr(39) + 'Final verdict. JSON only.' + chr(39) + ', model=MODEL_HEAVY, system=BEAR_SYSTEM, temperature=0.65)')
content.append('    a3b, bs3 = _parse_response(r3_bull, bull_base)')
content.append('    a3r, br3 = _parse_response(r3_bear, bear_base)')
content.append('    bull_scores.append(bs3); bear_scores.append(br3)')
content.append('    history.append({' + chr(39) + 'round' + chr(39) + ': 3, ' + chr(39) + 'bull' + chr(39) + ': a3b, ' + chr(39) + 'bear' + chr(39) + ': a3r})')
content.append('    print(' + chr(39) + '      Round 3 -- Bull: ' + chr(39) + ' + str(bs3) + ' + chr(39) + '% | Bear: ' + chr(39) + ' + str(br3) + ' + chr(39) + '%' + chr(39) + ')')
content.append('    avg_bull = round(sum(bull_scores) / 3, 1)')
content.append('    avg_bear = round(sum(bear_scores) / 3, 1)')
content.append('    margin   = round(abs(avg_bull - avg_bear), 1)')
content.append('    is_tie   = margin < 8')
content.append('    winner   = ' + chr(39) + 'TIE' + chr(39) + ' if is_tie else (' + chr(39) + 'BULL' + chr(39) + ' if avg_bull > avg_bear else ' + chr(39) + 'BEAR' + chr(39) + ')')
content.append('    return {' + chr(39) + 'history' + chr(39) + ': history, ' + chr(39) + 'avg_bull_confidence' + chr(39) + ': avg_bull, ' + chr(39) + 'avg_bear_confidence' + chr(39) + ': avg_bear,')
content.append('            ' + chr(39) + 'margin' + chr(39) + ': margin, ' + chr(39) + 'winner' + chr(39) + ': winner, ' + chr(39) + 'is_tie' + chr(39) + ': is_tie,')
content.append('            ' + chr(39) + 'final_bull' + chr(39) + ': a3b, ' + chr(39) + 'final_bear' + chr(39) + ': a3r, ' + chr(39) + 'round_scores' + chr(39) + ': list(zip(bull_scores, bear_scores))}')
content.append('')
with open('agents/debate.py', 'w', encoding='utf-8') as f:
    f.write(chr(10).join(content))
print('debate.py written OK')