content = open('utils/ollama_client.py', 'w', encoding='utf-8')
content.write('import requests, json, re, time' + chr(10))
content.write('from config import OLLAMA_BASE, MODEL_HEAVY, MODEL_LIGHT' + chr(10) + chr(10))
content.write('def _strip(t): return re.sub(r' + chr(39) + chr(60) + 'think>[\\s\\S]*?' + chr(60) + '/think>' + chr(39) + ', ' + chr(39) + chr(39) + ', t, flags=re.IGNORECASE).strip()' + chr(10) + chr(10))
content.write('def chat(prompt, model=MODEL_HEAVY, system=None, temperature=0.7, timeout=300):' + chr(10))
content.write('    msgs = []' + chr(10))
content.write('    if system: msgs.append({' + chr(39) + 'role' + chr(39) + ': ' + chr(39) + 'system' + chr(39) + ', ' + chr(39) + 'content' + chr(39) + ': system})' + chr(10))
content.write('    msgs.append({' + chr(39) + 'role' + chr(39) + ': ' + chr(39) + 'user' + chr(39) + ', ' + chr(39) + 'content' + chr(39) + ': prompt})' + chr(10))
content.write('    for attempt in range(3):' + chr(10))
content.write('        try:' + chr(10))
content.write('            r = requests.post(OLLAMA_BASE + ' + chr(39) + '/api/chat' + chr(39) + ', json={' + chr(39) + 'model' + chr(39) + ': model, ' + chr(39) + 'messages' + chr(39) + ': msgs, ' + chr(39) + 'stream' + chr(39) + ': False, ' + chr(39) + 'options' + chr(39) + ': {' + chr(39) + 'temperature' + chr(39) + ': temperature, ' + chr(39) + 'num_predict' + chr(39) + ': 800}}, timeout=timeout)' + chr(10))
content.write('            r.raise_for_status()' + chr(10))
content.write('            return _strip(r.json()[' + chr(39) + 'message' + chr(39) + '][' + chr(39) + 'content' + chr(39) + '])' + chr(10))
content.write('        except requests.exceptions.ReadTimeout:' + chr(10))
content.write('            print(' + chr(39) + '[ollama] timeout attempt ' + chr(39) + ' + str(attempt+1), flush=True)' + chr(10))
content.write('            time.sleep(5)' + chr(10))
content.write('        except Exception as e:' + chr(10))
content.write('            print(' + chr(39) + '[ollama] error: ' + chr(39) + ' + str(e), flush=True)' + chr(10))
content.write('            time.sleep(5)' + chr(10))
content.write('    return ' + chr(39) + 'ERROR: timeout' + chr(39) + chr(10) + chr(10))
content.write('def extract_confidence(text):' + chr(10))
content.write('    text = _strip(text)' + chr(10))
content.write('    lines = [l.strip() for l in text.strip().split(chr(10)) if l.strip()]' + chr(10))
content.write('    for line in reversed(lines):' + chr(10))
content.write('        m = re.search(r' + chr(39) + '[Cc]onfidence[:\\s]+(\\d{2,3})\\s*%?' + chr(39) + ', line)' + chr(10))
content.write('        if m:' + chr(10))
content.write('            v = int(m.group(1))' + chr(10))
content.write('            if 10 <= v <= 99: return v' + chr(10))
content.write('    all_m = re.findall(r' + chr(39) + '\\b(\\d{2,3})\\s*%' + chr(39) + ', text)' + chr(10))
content.write('    for v in reversed(all_m):' + chr(10))
content.write('        v = int(v)' + chr(10))
content.write('        if 40 <= v <= 95: return v' + chr(10))
content.write('    tl = text.lower()' + chr(10))
content.write('    if any(p in tl for p in [' + chr(39) + 'strongly bullish' + chr(39) + ', ' + chr(39) + 'highly confident' + chr(39) + ', ' + chr(39) + 'strong bull' + chr(39) + ']): return 75' + chr(10))
content.write('    if any(p in tl for p in [' + chr(39) + 'bullish' + chr(39) + ', ' + chr(39) + 'rise' + chr(39) + ', ' + chr(39) + 'upside' + chr(39) + ', ' + chr(39) + 'long' + chr(39) + ']): return 63' + chr(10))
content.write('    if any(p in tl for p in [' + chr(39) + 'strongly bearish' + chr(39) + ', ' + chr(39) + 'highly bearish' + chr(39) + ']): return 74' + chr(10))
content.write('    if any(p in tl for p in [' + chr(39) + 'bearish' + chr(39) + ', ' + chr(39) + 'fall' + chr(39) + ', ' + chr(39) + 'downside' + chr(39) + ', ' + chr(39) + 'short' + chr(39) + ']): return 62' + chr(10))
content.write('    return 57' + chr(10) + chr(10))
content.write('def extract_json(text):' + chr(10))
content.write('    text = _strip(text)' + chr(10))
content.write('    text = re.sub(r' + chr(39) + '`json|`' + chr(39) + ', ' + chr(39) + chr(39) + ', text).strip()' + chr(10))
content.write('    try: return json.loads(text)' + chr(10))
content.write('    except: pass' + chr(10))
content.write('    m = re.search(r' + chr(39) + '\\{[\\s\\S]+\\}' + chr(39) + ', text)' + chr(10))
content.write('    if m:' + chr(10))
content.write('        try: return json.loads(m.group())' + chr(10))
content.write('        except: pass' + chr(10))
content.write('    return {}' + chr(10))
content.close()
print('ollama_client.py written OK')