# master_build.py -- escribe todos los archivos del sistema v10
import os

def w(path, content):
    os.makedirs(os.path.dirname(path) if os.path.dirname(path) else '.', exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print('OK: ' + path)

# ATR CALCULATOR
w('utils/atr_calculator.py', chr(10).join([
    'import os, json',
    'from config import STATE_DIR',
    '',
    'def calculate_atr(prices, period=14):',
    '    if len(prices) < period + 1: return None',
    '    trs = []',
    '    for i in range(1, len(prices)):',
    '        h  = prices[i].get(' + chr(39) + 'high' + chr(39) + ',  prices[i][' + chr(39) + 'close' + chr(39) + '])',
    '        l  = prices[i].get(' + chr(39) + 'low' + chr(39) + ',   prices[i][' + chr(39) + 'close' + chr(39) + '])',
    '        pc = prices[i-1][' + chr(39) + 'close' + chr(39) + ']',
    '        trs.append(max(h - l, abs(h - pc), abs(l - pc)))',
    '    return round(sum(trs[-period:]) / period, 2)',
    '',
    'def get_atr_from_history():',
    '    try:',
    '        f = os.path.join(STATE_DIR, ' + chr(39) + 'price_history.json' + chr(39) + ')',
    '        if not os.path.exists(f): return None',
    '        with open(f, encoding=' + chr(39) + 'utf-8' + chr(39) + ') as fh: data = json.load(fh)',
    '        return calculate_atr(data.get(' + chr(39) + 'prices' + chr(39) + ', []))',
    '    except Exception as e:',
    '        print(' + chr(39) + '[ATR] error: ' + chr(39) + ' + str(e))',
    '        return None',
    '',
    'def get_swing_levels(price, atr, direction, risk_mult=1.5, reward_mult=3.0):',
    '    if not atr: atr = price * 0.008',
    '    sl = round(atr * risk_mult, 2)',
    '    tp = round(atr * reward_mult, 2)',
    '    if direction == ' + chr(39) + 'LONG' + chr(39) + ':',
    '        return {' + chr(39) + 'stop' + chr(39) + ': round(price-sl,2), ' + chr(39) + 'target' + chr(39) + ': round(price+tp,2), ' + chr(39) + 'sl_dist' + chr(39) + ': sl, ' + chr(39) + 'tp_dist' + chr(39) + ': tp, ' + chr(39) + 'rr' + chr(39) + ': round(tp/sl,2), ' + chr(39) + 'atr' + chr(39) + ': atr}',
    '    return {' + chr(39) + 'stop' + chr(39) + ': round(price+sl,2), ' + chr(39) + 'target' + chr(39) + ': round(price-tp,2), ' + chr(39) + 'sl_dist' + chr(39) + ': sl, ' + chr(39) + 'tp_dist' + chr(39) + ': tp, ' + chr(39) + 'rr' + chr(39) + ': round(tp/sl,2), ' + chr(39) + 'atr' + chr(39) + ': atr}',
]))

# RISK MANAGER con ATR
w('agents/risk_manager.py', chr(10).join([
    'from config import CAPITAL, MAX_RISK_PCT, MIN_RR',
    'from utils.atr_calculator import get_atr_from_history, get_swing_levels',
    '',
    'LEVERAGE = 30',
    'CONTRACT_SIZE = 100',
    '',
    'def calculate(debate_result, tech_data, price_data, account_balance=None):',
    '    balance   = account_balance or CAPITAL',
    '    price     = price_data.get(' + chr(39) + 'price' + chr(39) + ', 0)',
    '    winner    = debate_result.get(' + chr(39) + 'winner' + chr(39) + ', ' + chr(39) + 'TIE' + chr(39) + ')',
    '    margin    = debate_result.get(' + chr(39) + 'margin' + chr(39) + ', 0)',
    '    if winner == ' + chr(39) + 'TIE' + chr(39) + ':',
    '        return {' + chr(39) + 'valid' + chr(39) + ': False, ' + chr(39) + 'reason' + chr(39) + ': ' + chr(39) + 'Debate ended in tie' + chr(39) + '}',
    '    win_prob  = (debate_result.get(' + chr(39) + 'avg_bull_confidence' + chr(39) + ', 50) if winner == ' + chr(39) + 'BULL' + chr(39) + ' else debate_result.get(' + chr(39) + 'avg_bear_confidence' + chr(39) + ', 50)) / 100',
    '    direction = ' + chr(39) + 'LONG' + chr(39) + ' if winner == ' + chr(39) + 'BULL' + chr(39) + ' else ' + chr(39) + 'SHORT' + chr(39),
    '    atr = get_atr_from_history()',
    '    if not atr:',
    '        atr = price * 0.008',
    '        print(' + chr(39) + '[risk] ATR fallback: ' + chr(39) + ' + str(round(atr,2)))',
    '    else:',
    '        print(' + chr(39) + '[risk] ATR real: ' + chr(39) + ' + str(atr))',
    '    lv = get_swing_levels(price, atr, direction)',
    '    stop, target, sl_dist, tp_dist, rr = lv[' + chr(39) + 'stop' + chr(39) + '], lv[' + chr(39) + 'target' + chr(39) + '], lv[' + chr(39) + 'sl_dist' + chr(39) + '], lv[' + chr(39) + 'tp_dist' + chr(39) + '], lv[' + chr(39) + 'rr' + chr(39) + ']',
    '    if sl_dist < 1: return {' + chr(39) + 'valid' + chr(39) + ': False, ' + chr(39) + 'reason' + chr(39) + ': ' + chr(39) + 'SL too small' + chr(39) + '}',
    '    if round(rr, 4) < MIN_RR: return {' + chr(39) + 'valid' + chr(39) + ': False, ' + chr(39) + 'reason' + chr(39) + ': ' + chr(39) + 'RR ' + chr(39) + ' + str(round(rr,2)) + ' + chr(39) + ' below min ' + chr(39) + ' + str(MIN_RR)}',
    '    kelly_f  = max(0, (win_prob * (rr + 1) - 1) / rr)',
    '    kelly_f  = min(kelly_f, MAX_RISK_PCT)',
    '    risk_usd = round(min(balance * kelly_f, balance * MAX_RISK_PCT), 2)',
    '    lot_size = max(0.01, round(risk_usd / (sl_dist * CONTRACT_SIZE), 2))',
    '    notional = lot_size * CONTRACT_SIZE * price',
    '    margin_needed = notional / LEVERAGE',
    '    if margin_needed > balance * 0.30:',
    '        lot_size = max(0.01, round((balance * 0.30 * LEVERAGE) / (CONTRACT_SIZE * price), 2))',
    '        risk_usd = round(lot_size * CONTRACT_SIZE * sl_dist, 2)',
    '        margin_needed = round(lot_size * CONTRACT_SIZE * price / LEVERAGE, 2)',
    '    return {' + chr(39) + 'valid' + chr(39) + ': True, ' + chr(39) + 'direction' + chr(39) + ': direction, ' + chr(39) + 'entry' + chr(39) + ': round(price,2),',
    '            ' + chr(39) + 'stop_loss' + chr(39) + ': stop, ' + chr(39) + 'take_profit' + chr(39) + ': target,',
    '            ' + chr(39) + 'sl_distance' + chr(39) + ': sl_dist, ' + chr(39) + 'tp_distance' + chr(39) + ': tp_dist,',
    '            ' + chr(39) + 'risk_reward' + chr(39) + ': rr, ' + chr(39) + 'win_probability' + chr(39) + ': round(win_prob*100,1),',
    '            ' + chr(39) + 'kelly_fraction' + chr(39) + ': round(kelly_f*100,2), ' + chr(39) + 'risk_usd' + chr(39) + ': risk_usd,',
    '            ' + chr(39) + 'contracts' + chr(39) + ': lot_size, ' + chr(39) + 'margin_needed' + chr(39) + ': round(margin_needed,2),',
    '            ' + chr(39) + 'atr_used' + chr(39) + ': atr, ' + chr(39) + 'debate_margin' + chr(39) + ': margin, ' + chr(39) + 'balance_used' + chr(39) + ': balance}',
]))

# MARKET DATA (DXY, Fear&Greed via FRED)
w('utils/market_data.py', chr(10).join([
    'import requests, os',
    'from dotenv import load_dotenv',
    'load_dotenv()',
    'FRED_KEY = os.getenv(' + chr(39) + 'FRED_KEY' + chr(39) + ', ' + chr(39) + chr(39) + ')',
    '',
    'def get_dxy():',
    '    if not FRED_KEY: return {' + chr(39) + 'value' + chr(39) + ': None, ' + chr(39) + 'source' + chr(39) + ': ' + chr(39) + 'no FRED key' + chr(39) + '}',
    '    try:',
    '        r = requests.get(' + chr(39) + 'https://api.stlouisfed.org/fred/series/observations' + chr(39) + ',',
    '            params={' + chr(39) + 'series_id' + chr(39) + ': ' + chr(39) + 'DTWEXBGS' + chr(39) + ', ' + chr(39) + 'api_key' + chr(39) + ': FRED_KEY, ' + chr(39) + 'file_type' + chr(39) + ': ' + chr(39) + 'json' + chr(39) + ', ' + chr(39) + 'limit' + chr(39) + ': 2, ' + chr(39) + 'sort_order' + chr(39) + ': ' + chr(39) + 'desc' + chr(39) + '}, timeout=8)',
    '        obs = r.json().get(' + chr(39) + 'observations' + chr(39) + ', [])',
    '        return {' + chr(39) + 'value' + chr(39) + ': float(obs[0][' + chr(39) + 'value' + chr(39) + ']), ' + chr(39) + 'date' + chr(39) + ': obs[0][' + chr(39) + 'date' + chr(39) + '], ' + chr(39) + 'source' + chr(39) + ': ' + chr(39) + 'FRED' + chr(39) + '} if obs else {' + chr(39) + 'value' + chr(39) + ': None, ' + chr(39) + 'source' + chr(39) + ': ' + chr(39) + 'empty' + chr(39) + '}',
    '    except Exception as e:',
    '        print(' + chr(39) + '[market_data] DXY error: ' + chr(39) + ' + str(e))',
    '        return {' + chr(39) + 'value' + chr(39) + ': None, ' + chr(39) + 'source' + chr(39) + ': ' + chr(39) + 'error' + chr(39) + '}',
    '',
    'def get_treasury_10y():',
    '    if not FRED_KEY: return {' + chr(39) + 'value' + chr(39) + ': None}',
    '    try:',
    '        r = requests.get(' + chr(39) + 'https://api.stlouisfed.org/fred/series/observations' + chr(39) + ',',
    '            params={' + chr(39) + 'series_id' + chr(39) + ': ' + chr(39) + 'DGS10' + chr(39) + ', ' + chr(39) + 'api_key' + chr(39) + ': FRED_KEY, ' + chr(39) + 'file_type' + chr(39) + ': ' + chr(39) + 'json' + chr(39) + ', ' + chr(39) + 'limit' + chr(39) + ': 2, ' + chr(39) + 'sort_order' + chr(39) + ': ' + chr(39) + 'desc' + chr(39) + '}, timeout=8)',
    '        obs = r.json().get(' + chr(39) + 'observations' + chr(39) + ', [])',
    '        return {' + chr(39) + 'value' + chr(39) + ': float(obs[0][' + chr(39) + 'value' + chr(39) + ']), ' + chr(39) + 'source' + chr(39) + ': ' + chr(39) + 'FRED' + chr(39) + '} if obs else {' + chr(39) + 'value' + chr(39) + ': None}',
    '    except: return {' + chr(39) + 'value' + chr(39) + ': None}',
    '',
    'def get_all():',
    '    dxy = get_dxy()',
    '    t10 = get_treasury_10y()',
    '    parts = []',
    '    if dxy.get(' + chr(39) + 'value' + chr(39) + '): parts.append(' + chr(39) + 'DXY: ' + chr(39) + ' + str(round(dxy[' + chr(39) + 'value' + chr(39) + '],2)))',
    '    if t10.get(' + chr(39) + 'value' + chr(39) + '): parts.append(' + chr(39) + '10Y Treasury: ' + chr(39) + ' + str(t10[' + chr(39) + 'value' + chr(39) + ']) + ' + chr(39) + chr(37) + chr(39) + ')',
    '    return {' + chr(39) + 'dxy' + chr(39) + ': dxy, ' + chr(39) + 'treasury_10y' + chr(39) + ': t10, ' + chr(39) + 'summary' + chr(39) + ': ' + chr(39) + ' | ' + chr(39) + '.join(parts) if parts else ' + chr(39) + 'No macro data' + chr(39) + '}',
]))

print('All files written OK')